// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: addon.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProductAddon = `-- name: CreateProductAddon :one
INSERT INTO "product_addon" (
    "tenant_id",
    "product_id",
    "name",
    "price"
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING "id", "tenant_id", "product_id", "name", "price", "created_at", "modified_at"
`

type CreateProductAddonParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
	Name      string
	Price     int64
}

type CreateProductAddonRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ProductID  uuid.UUID
	Name       string
	Price      int64
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) CreateProductAddon(ctx context.Context, arg CreateProductAddonParams) (CreateProductAddonRow, error) {
	row := q.db.QueryRow(ctx, createProductAddon,
		arg.TenantID,
		arg.ProductID,
		arg.Name,
		arg.Price,
	)
	var i CreateProductAddonRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
