// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: branch.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO "branch" (
    "tenant_id",
    "name",
    "code"
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING "id", "tenant_id", "name", "code", "created_at", "modified_at"
`

type CreateBranchParams struct {
	TenantID uuid.UUID
	Name     string
	Code     string
}

type CreateBranchRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	Code       string
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (CreateBranchRow, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.TenantID, arg.Name, arg.Code)
	var i CreateBranchRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
