// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: cart.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCart = `-- name: CreateCart :one
INSERT INTO "cart" (
    "tenant_id",
    "user_uid",
    "is_active"
)
VALUES (
    $1,
    $2,
    TRUE
)
RETURNING "id", "tenant_id", "user_uid", "is_active", "created_at", "modified_at"
`

type CreateCartParams struct {
	TenantID uuid.UUID
	UserUid  uuid.UUID
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.TenantID, arg.UserUid)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO "cart_item" (
    "tenant_id",
    "cart_id",
    "product_id",
    "quantity",
    "unit_price",
    "vat_percent",
    "note",
    "prescription_ref"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING "id", "tenant_id", "cart_id", "product_id", "quantity", "unit_price", "vat_percent", "note", "prescription_ref", "created_at", "modified_at"
`

type CreateCartItemParams struct {
	TenantID        uuid.UUID
	CartID          uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	UnitPrice       int64
	VatPercent      pgtype.Numeric
	Note            pgtype.Text
	PrescriptionRef pgtype.Text
}

type CreateCartItemRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	CartID          uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	UnitPrice       int64
	VatPercent      pgtype.Numeric
	Note            pgtype.Text
	PrescriptionRef pgtype.Text
	CreatedAt       time.Time
	ModifiedAt      time.Time
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CreateCartItemRow, error) {
	row := q.db.QueryRow(ctx, createCartItem,
		arg.TenantID,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.VatPercent,
		arg.Note,
		arg.PrescriptionRef,
	)
	var i CreateCartItemRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.VatPercent,
		&i.Note,
		&i.PrescriptionRef,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getActiveCartByTenantAndUser = `-- name: GetActiveCartByTenantAndUser :one
SELECT "id", "tenant_id", "user_uid", "is_active", "created_at", "modified_at"
FROM "cart"
WHERE "tenant_id" = $1
  AND "user_uid" = $2
  AND "is_active" = TRUE
LIMIT 1
`

type GetActiveCartByTenantAndUserParams struct {
	TenantID uuid.UUID
	UserUid  uuid.UUID
}

func (q *Queries) GetActiveCartByTenantAndUser(ctx context.Context, arg GetActiveCartByTenantAndUserParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getActiveCartByTenantAndUser, arg.TenantID, arg.UserUid)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserUid,
		&i.IsActive,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
