// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: discount.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscount = `-- name: CreateDiscount :one
INSERT INTO "discount" (
    "tenant_id",
    "product_id",
    "code",
    "name",
    "type",
    "value",
    "starts_at",
    "ends_at"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING "id", "tenant_id", "product_id", "code", "name", "type", "value", "starts_at", "ends_at", "created_at", "modified_at"
`

type CreateDiscountParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
	Code      string
	Name      string
	Type      DiscountType
	Value     pgtype.Numeric
	StartsAt  time.Time
	EndsAt    time.Time
}

type CreateDiscountRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ProductID  uuid.UUID
	Code       string
	Name       string
	Type       DiscountType
	Value      pgtype.Numeric
	StartsAt   time.Time
	EndsAt     time.Time
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) CreateDiscount(ctx context.Context, arg CreateDiscountParams) (CreateDiscountRow, error) {
	row := q.db.QueryRow(ctx, createDiscount,
		arg.TenantID,
		arg.ProductID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Value,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i CreateDiscountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Value,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
