// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: inventory.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
)

const getInventoryByTenantAndProduct = `-- name: GetInventoryByTenantAndProduct :one
SELECT "id", "tenant_id", "product_id", "in_stock", "reserved", "created_at", "modified_at"
FROM "inventory"
WHERE "tenant_id" = $1
  AND "product_id" = $2
LIMIT 1
`

type GetInventoryByTenantAndProductParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetInventoryByTenantAndProduct(ctx context.Context, arg GetInventoryByTenantAndProductParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByTenantAndProduct, arg.TenantID, arg.ProductID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.InStock,
		&i.Reserved,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const reserveInventory = `-- name: ReserveInventory :one
UPDATE "inventory"
SET
    "reserved" = "reserved" + $3,
    "modified_at" = CURRENT_TIMESTAMP
WHERE "tenant_id" = $1
  AND "product_id" = $2
  AND ("in_stock" - "reserved") >= $3
RETURNING "id", "tenant_id", "product_id", "in_stock", "reserved", "created_at", "modified_at"
`

type ReserveInventoryParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
	Reserved  int32
}

func (q *Queries) ReserveInventory(ctx context.Context, arg ReserveInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, reserveInventory, arg.TenantID, arg.ProductID, arg.Reserved)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.InStock,
		&i.Reserved,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const upsertInventoryForProduct = `-- name: UpsertInventoryForProduct :one
INSERT INTO "inventory" (
    "tenant_id",
    "product_id",
    "in_stock",
    "reserved"
)
VALUES (
    $1,
    $2,
    $3,
    0
)
ON CONFLICT ("tenant_id", "product_id")
DO UPDATE SET
    "in_stock" = EXCLUDED."in_stock",
    "modified_at" = CURRENT_TIMESTAMP
RETURNING "id", "tenant_id", "product_id", "in_stock", "reserved", "created_at", "modified_at"
`

type UpsertInventoryForProductParams struct {
	TenantID  uuid.UUID
	ProductID uuid.UUID
	InStock   int32
}

func (q *Queries) UpsertInventoryForProduct(ctx context.Context, arg UpsertInventoryForProductParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, upsertInventoryForProduct, arg.TenantID, arg.ProductID, arg.InStock)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.InStock,
		&i.Reserved,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
