// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountCartItemsByTenantAndCart(ctx context.Context, arg CountCartItemsByTenantAndCartParams) (int32, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (CreateBranchRow, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CreateCartItemRow, error)
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) (CreateDiscountRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (CreatePaymentMethodRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateProductAddon(ctx context.Context, arg CreateProductAddonParams) (CreateProductAddonRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	EnsureDefaultCashPaymentMethod(ctx context.Context, tenantID uuid.UUID) error
	GetActiveCartByTenantAndUser(ctx context.Context, arg GetActiveCartByTenantAndUserParams) (Cart, error)
	GetCartByTenantAndID(ctx context.Context, arg GetCartByTenantAndIDParams) (Cart, error)
	GetDefaultCashPaymentMethodByTenant(ctx context.Context, tenantID uuid.UUID) (GetDefaultCashPaymentMethodByTenantRow, error)
	GetInventoryByTenantAndProduct(ctx context.Context, arg GetInventoryByTenantAndProductParams) (Inventory, error)
	GetLatestSubscriptionByTenant(ctx context.Context, tenantID uuid.UUID) (GetLatestSubscriptionByTenantRow, error)
	GetOrderByTenantAndID(ctx context.Context, arg GetOrderByTenantAndIDParams) (GetOrderByTenantAndIDRow, error)
	GetPaymentMethodByTenantAndID(ctx context.Context, arg GetPaymentMethodByTenantAndIDParams) (GetPaymentMethodByTenantAndIDRow, error)
	GetProductByTenantAndID(ctx context.Context, arg GetProductByTenantAndIDParams) (GetProductByTenantAndIDRow, error)
	GetSessionByTenant(ctx context.Context, arg GetSessionByTenantParams) (Session, error)
	GetTenantByDomain(ctx context.Context, domain string) (GetTenantByDomainRow, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (GetTenantByIDRow, error)
	GetTenantBySlug(ctx context.Context, slug string) (GetTenantBySlugRow, error)
	GetUserByTenantAndEmail(ctx context.Context, arg GetUserByTenantAndEmailParams) (GetUserByTenantAndEmailRow, error)
	GetUserByTenantAndUID(ctx context.Context, arg GetUserByTenantAndUIDParams) (GetUserByTenantAndUIDRow, error)
	ListCartItemsByTenantAndCart(ctx context.Context, arg ListCartItemsByTenantAndCartParams) ([]ListCartItemsByTenantAndCartRow, error)
	ListPaymentMethodsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListPaymentMethodsByTenantRow, error)
	MarkOrderPaidByTenant(ctx context.Context, arg MarkOrderPaidByTenantParams) (MarkOrderPaidByTenantRow, error)
	ReserveInventory(ctx context.Context, arg ReserveInventoryParams) (Inventory, error)
	SetCartInactive(ctx context.Context, arg SetCartInactiveParams) error
	UpdateOrderStatusByTenant(ctx context.Context, arg UpdateOrderStatusByTenantParams) (UpdateOrderStatusByTenantRow, error)
	UpsertInventoryForProduct(ctx context.Context, arg UpsertInventoryForProductParams) (Inventory, error)
}

var _ Querier = (*Queries)(nil)
