// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: session.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO "session" (
	"tenant_id"
	, "uid"
	, "user_email"
	, "refresh_token"
	, "user_agent"
	, "client_ip"
	, "is_blocked"
	, "expires_at"
	)
VALUES (
	$1
	, $2
	, $3
	, $4
	, $5
	, $6
	, $7
	, $8
	) RETURNING id, uid, user_email, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, tenant_id
`

type CreateSessionParams struct {
	TenantID     uuid.UUID
	UID          uuid.UUID
	UserEmail    string
	RefreshToken string
	UserAgent    string
	ClientIP     string
	IsBlocked    bool
	ExpiresAt    time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TenantID,
		arg.UID,
		arg.UserEmail,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIP,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UID,
		&i.UserEmail,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getSessionByTenant = `-- name: GetSessionByTenant :one
SELECT id, uid, user_email, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at, tenant_id
FROM "session"
WHERE "tenant_id" = $1
	AND "uid" = $2 LIMIT 1
`

type GetSessionByTenantParams struct {
	TenantID uuid.UUID
	UID      uuid.UUID
}

func (q *Queries) GetSessionByTenant(ctx context.Context, arg GetSessionByTenantParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTenant, arg.TenantID, arg.UID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UID,
		&i.UserEmail,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIP,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}
