// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: subscription.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO "subscription" (
    "tenant_id",
    "plan",
    "status",
    "starts_at",
    "ends_at"
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING "id", "tenant_id", "plan", "status", "starts_at", "ends_at", "created_at", "modified_at"
`

type CreateSubscriptionParams struct {
	TenantID uuid.UUID
	Plan     string
	Status   SubscriptionStatus
	StartsAt time.Time
	EndsAt   time.Time
}

type CreateSubscriptionRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Plan       string
	Status     SubscriptionStatus
	StartsAt   time.Time
	EndsAt     time.Time
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CreateSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.Plan,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i CreateSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
