// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tenant.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO "tenant" (
	"name",
	"slug",
	"domain",
	"type"
)
VALUES (
	$1,
	$2,
	$3,
	$4
)
RETURNING "id", "name", "slug", "domain", "type", "created_at", "modified_at"
`

type CreateTenantParams struct {
	Name   string
	Slug   string
	Domain string
	Type   TenantType
}

type CreateTenantRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Domain     string
	Type       TenantType
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Type,
	)
	var i CreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Type,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getLatestSubscriptionByTenant = `-- name: GetLatestSubscriptionByTenant :one
SELECT "id", "tenant_id", "plan", "status", "starts_at", "ends_at", "created_at", "modified_at"
FROM "subscription"
WHERE "tenant_id" = $1
	AND "deleted_at" IS NULL
ORDER BY "created_at" DESC
LIMIT 1
`

type GetLatestSubscriptionByTenantRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Plan       string
	Status     SubscriptionStatus
	StartsAt   time.Time
	EndsAt     time.Time
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) GetLatestSubscriptionByTenant(ctx context.Context, tenantID uuid.UUID) (GetLatestSubscriptionByTenantRow, error) {
	row := q.db.QueryRow(ctx, getLatestSubscriptionByTenant, tenantID)
	var i GetLatestSubscriptionByTenantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT "id", "name", "slug", "domain", "type", "created_at", "modified_at"
FROM "tenant"
WHERE "domain" = $1
	AND "deleted_at" IS NULL
LIMIT 1
`

type GetTenantByDomainRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Domain     string
	Type       TenantType
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (GetTenantByDomainRow, error) {
	row := q.db.QueryRow(ctx, getTenantByDomain, domain)
	var i GetTenantByDomainRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Type,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT "id", "name", "slug", "domain", "type", "created_at", "modified_at"
FROM "tenant"
WHERE "id" = $1
	AND "deleted_at" IS NULL
LIMIT 1
`

type GetTenantByIDRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Domain     string
	Type       TenantType
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Type,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT "id", "name", "slug", "domain", "type", "created_at", "modified_at"
FROM "tenant"
WHERE "slug" = $1
	AND "deleted_at" IS NULL
LIMIT 1
`

type GetTenantBySlugRow struct {
	ID         uuid.UUID
	Name       string
	Slug       string
	Domain     string
	Type       TenantType
	CreatedAt  time.Time
	ModifiedAt time.Time
}

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (GetTenantBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i GetTenantBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Type,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
